import { INestApplication } from '@nestjs/common';
import { DocumentBuilder, SwaggerModule, OpenAPIObject } from '@nestjs/swagger';

/**
 * One definition of the OpenAPI document, shared by the running app (which serves Swagger
 * UI at /api/v1/docs) and `npm run openapi:generate` (which writes openapi.json to disk).
 *
 * Sharing it is the point: a hand-maintained spec file drifts from the code the moment
 * someone adds a route, and a spec that lies is worse than no spec. This one is derived
 * from the controllers and DTOs themselves, so it cannot describe an endpoint that does
 * not exist or miss one that does.
 */
export function buildOpenApiDocument(app: INestApplication): OpenAPIObject {
  const config = new DocumentBuilder()
    .setTitle('Multi-Tenant Feature Flag Service')
    .setDescription(
      [
        'A multi-tenant configuration and feature flag service — a simplified LaunchDarkly.',
        '',
        '### Authentication',
        '',
        'Two credentials exist, and they are not interchangeable:',
        '',
        '| Header | Used by | Obtained from |',
        '|---|---|---|',
        '| `x-api-key` | Everything scoped to a tenant | Returned once when the tenant is registered |',
        '| `x-admin-key` | Tenant registration only | Generated by Terraform, stored in Secret Manager |',
        '',
        'The tenant is **always** derived from the API key, never from the request body or URL.',
        'A `tenantId` in a path is checked for agreement with the key and returns `403` on mismatch;',
        'a `tenant_id` in an evaluation body is treated the same way. This is what enforces tenant',
        "isolation — there is no request field a caller can change to reach another tenant's data.",
        '',
        '`ADMIN_API_KEY` is unset locally and in CI, so the admin guard is a no-op there.',
        '',
        '### Determinism',
        '',
        'Percentage rollouts are deterministic. The same `user_id` always receives the same value',
        'for a given flag configuration, because bucketing is a SHA-256 hash of the flag key and',
        'user id mapped to 0–99 rather than stored state. Any instance computes the same answer,',
        'and no sticky sessions are required.',
        '',
        'Rollout gating and variant selection use **different salts**, so the two decisions are',
        'independent. Sharing one hash would silently give every gated-in user the first variant.',
        '',
        '### Rate limiting',
        '',
        "Limits are per tenant, keyed on the API key, so one noisy tenant cannot consume another's",
        'budget. Exceeding the limit returns `429`.',
      ].join('\n'),
    )
    .setVersion('1.0')
    .addServer('http://localhost:3000', 'Local (Docker Compose)')
    .addServer(
      'https://feature-flag-service-staging-dhqwxiey3q-uc.a.run.app',
      'Staging (Cloud Run)',
    )
    .addServer(
      'https://feature-flag-service-production-<hash>-uc.a.run.app',
      'Production (Cloud Run)',
    )
    .addApiKey(
      {
        type: 'apiKey',
        name: 'x-api-key',
        in: 'header',
        description:
          'Tenant API key, returned once at registration. Identifies the tenant for every scoped operation.',
      },
      'api-key',
    )
    .addApiKey(
      {
        type: 'apiKey',
        name: 'x-admin-key',
        in: 'header',
        description:
          'Platform admin key, required for tenant registration wherever ADMIN_API_KEY is configured. Read it with: gcloud secrets versions access latest --secret=feature-flag-service-<env>-admin-api-key',
      },
      'admin-key',
    )
    .addTag('Tenants', 'Register tenants and inspect the authenticated tenant')
    .addTag('Feature Flags', 'Create, list, update and archive flags')
    .addTag(
      'Evaluation',
      'Resolve flag values for a user — the read-hot path of the service',
    )
    .addTag('Audit', 'Immutable, append-only change history')
    .addTag('Real-Time', 'Server-Sent Events for live flag-change distribution')
    .addTag('Operations', 'Health checks and Prometheus metrics')
    .build();

  const document = SwaggerModule.createDocument(app, config);

  // Mark unauthenticated operations as explicitly public.
  //
  // In OpenAPI an operation with no `security` key inherits the document default, which
  // reads as "unspecified" rather than "open" — validators flag it, and a client generator
  // cannot tell a deliberately public endpoint from one where the author forgot. An empty
  // array is the spec's way of saying "no credentials required".
  //
  // Every authenticated controller carries @ApiSecurity, so anything still lacking security
  // here is public by design: /health and /metrics, both of which are probe targets that
  // must be reachable without credentials.
  for (const pathItem of Object.values(document.paths)) {
    for (const operation of Object.values(pathItem)) {
      if (
        operation &&
        typeof operation === 'object' &&
        'responses' in operation &&
        !('security' in operation)
      ) {
        (operation as { security: unknown[] }).security = [];
      }
    }
  }

  return document;
}

export function setupSwagger(app: INestApplication): void {
  const document = buildOpenApiDocument(app);

  // Served under the global prefix: /api/v1/docs (UI) and /api/v1/docs-json (raw spec).
  SwaggerModule.setup('api/v1/docs', app, document, {
    jsonDocumentUrl: 'api/v1/docs-json',
    customSiteTitle: 'Feature Flag Service API',
    swaggerOptions: {
      // Persist the API key across page reloads so "Try it out" stays usable.
      persistAuthorization: true,
      docExpansion: 'list',
      tagsSorter: 'alpha',
    },
  });
}
