import { INestApplication } from '@nestjs/common';
import { DocumentBuilder, SwaggerModule, OpenAPIObject } from '@nestjs/swagger';

export function buildOpenApiDocument(app: INestApplication): OpenAPIObject {
  const config = new DocumentBuilder()
    .setTitle('Multi-Tenant Feature Flag Service')
    .setDescription(
      [
        'A multi-tenant configuration and feature flag service — a simplified LaunchDarkly.',
        '',
        '### Authentication',
        '',
        'Two credentials exist, and they are not interchangeable:',
        '',
        '| Header | Used by | Obtained from |',
        '|---|---|---|',
        '| `x-api-key` | Everything scoped to a tenant | Returned once when the tenant is registered |',
        '| `x-admin-key` | Tenant registration only | Generated by Terraform, stored in Secret Manager |',
        '',
        'The tenant is **always** derived from the API key, never from the request body or URL.',
        'A `tenantId` in a path is checked for agreement with the key and returns `403` on mismatch;',
        'a `tenant_id` in an evaluation body is treated the same way. This is what enforces tenant',
        "isolation — there is no request field a caller can change to reach another tenant's data.",
        '',
        '`ADMIN_API_KEY` is unset locally and in CI, so the admin guard is a no-op there.',
        '',
        '### Determinism',
        '',
        'Percentage rollouts are deterministic. The same `user_id` always receives the same value',
        'for a given flag configuration, because bucketing is a SHA-256 hash of the flag key and',
        'user id mapped to 0–99 rather than stored state. Any instance computes the same answer,',
        'and no sticky sessions are required.',
        '',
        'Rollout gating and variant selection use **different salts**, so the two decisions are',
        'independent. Sharing one hash would silently give every gated-in user the first variant.',
        '',
        '### Rate limiting',
        '',
        "Limits are per tenant, keyed on the API key, so one noisy tenant cannot consume another's",
        'budget. Exceeding the limit returns `429`.',
      ].join('\n'),
    )
    .setVersion('1.0')
    // A RELATIVE server, and it must stay first.
    //
    // Swagger UI sends "Try it out" requests to whichever server is selected, defaulting to
    // the first in this list. With an absolute `http://localhost:3000` first, the deployed
    // documentation sent every request to the reader's OWN machine — so a staging API key
    // was validated against whatever happened to be running locally, and came back 401.
    // The endpoint looked broken when the credential was fine.
    //
    // "/" resolves to the origin currently serving the page, so the docs are always correct
    // wherever they run: localhost when local, Cloud Run when deployed. It also means no
    // deploy URL has to be hardcoded here at all.
    .addServer('/', 'This server (whichever origin is serving these docs)')
    .addApiKey(
      {
        type: 'apiKey',
        name: 'x-api-key',
        in: 'header',
        description:
          'Tenant API key, returned once at registration. Identifies the tenant for every scoped operation.',
      },
      'api-key',
    )
    .addApiKey(
      {
        type: 'apiKey',
        name: 'x-admin-key',
        in: 'header',
        description:
          'Platform admin key, required for tenant registration wherever ADMIN_API_KEY is configured. Read it with: gcloud secrets versions access latest --secret=feature-flag-service-<env>-admin-api-key',
      },
      'admin-key',
    )
    .addTag('Tenants', 'Register tenants and inspect the authenticated tenant')
    .addTag('Feature Flags', 'Create, list, update and archive flags')
    .addTag(
      'Evaluation',
      'Resolve flag values for a user — the read-hot path of the service',
    )
    .addTag('Audit', 'Immutable, append-only change history')
    .addTag('Real-Time', 'Server-Sent Events for live flag-change distribution')
    .addTag('Operations', 'Health checks and Prometheus metrics')
    .build();

  const document = SwaggerModule.createDocument(app, config);

  for (const pathItem of Object.values(document.paths)) {
    for (const operation of Object.values(pathItem)) {
      if (
        operation &&
        typeof operation === 'object' &&
        'responses' in operation &&
        !('security' in operation)
      ) {
        (operation as { security: unknown[] }).security = [];
      }
    }
  }

  return document;
}

export function setupSwagger(app: INestApplication): void {
  const document = buildOpenApiDocument(app);

  SwaggerModule.setup('api/v1/docs', app, document, {
    jsonDocumentUrl: 'api/v1/docs-json',
    customSiteTitle: 'Feature Flag Service API',
    swaggerOptions: {
      persistAuthorization: true,
      docExpansion: 'list',
      tagsSorter: 'alpha',
    },
  });
}
